### ISSUE TITLE
Powerspill Case and Top .stl files are the same file.

### ISSUE THREAD

**Issue by senseored** [Sandalmoth/keyboards#1]
[powerspill_12_frame_4_case_3_case.stl](https://github.com/Sandalmoth/keyboards/blob/master/powerspill/stl/powerspill_12_frame_4_case_3_case.stl) and [powerspill_12_frame_4_case_3_top.stl](https://github.com/Sandalmoth/keyboards/blob/master/powerspill/stl/powerspill_12_frame_4_case_3_top.stl) are the same files. I could be wrong, but I am assuming the case one should be a bottom for the keyboard?

**Comment by Sandalmoth** [comment]
Yep, seems like I uploaded the wrong file. Should be fixed now.
